### ISSUE TITLE
An error happening when webworkers are implemented on next js 

### ISSUE THREAD

**Issue by muhammedfouzan** [GMOD/jbrowse-react-linear-genome-view-nextjs-demo#1]
<img width="770" alt="image" src="https://github.com/GMOD/jbrowse-react-linear-genome-view-nextjs-demo/assets/150672951/cacc8935-574f-4711-95da-f5c9f8b316b4">

 "@jbrowse/core": "^2.10.2",
    "@jbrowse/react-linear-genome-view": "^2.10.1",
    "next": "^14.0.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

state = createViewState({
        assembly: config?.assembly[0],
        tracks: config?.tracks,
        defaultSession: config?.defaultSession,
        aggregateTextSearchAdapters: config?.aggregateTextSearchAdapters,
        // configuration: config?.configuration,
        configuration: {
          rpc: {
            defaultDriver: "WebWorkerRpcDriver",
          },
        },
        makeWorkerInstance,

        hydrateFn: hydrateRoot,
        createRootFn: createRoot,
      });

**Comment by muhammedfouzan** [comment]
It is a weird issue, I cloned your repo, updated its package.json and next config file of mine, and still your repo works, but the same exact does not work in mine.
I used the same jbrowse config and page component of your repo in mine.
<img width="1504" alt="image" src="https://github.com/GMOD/jbrowse-react-linear-genome-view-nextjs-demo/assets/150672951/85957242-66d7-4acc-b10b-e1467886ae7e">

what else could be the reason, its not the package.json or next.config.ts. since I tried those of mine in yours

**Comment by cmdcolin** [comment]
can you get exact versions of packages used with e.g. "yarn why @jbrowse/react-linear-genome-view", "yarn why next", "yarn why react"

**Comment by muhammedfouzan** [comment]
=> Found "@jbrowse/react-linear-genome-view@2.11.1"
=> Found "react@18.3.1"
=> Found "next@14.2.3"

**Comment by muhammedfouzan** [comment]
I tried installing all module with yarn, instead of npm and it fixed the issue for me. Weird though, I'm assuming it to be something to do with my package-lock.json
